config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show, :index] do
    post "generate_bill"
  end
  resources :bills, only: [] do
    post "pay"
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    post "create_for/:user_id", on: :collection, as: :create_for, action: :create_for
    post "clone_package/:user_id", as: :clone_package, action: :clone_package
  end
  resources :services, except: [:new, :edit] do
    post "disable"
    post "enable"
  end
  resources :packages

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#overview", as: :root_authed
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", as: :root_unauthed
    end
  end

  resources :subscription_rules, only: [:index, :create, :update]

end

app/models/service.rb
class Service < ActiveRecord::Base
  validates_presence_of :price, :name, :description, :num_early_term_days
  validates_uniqueness_of :name
  validates_numericality_of :price, :num_early_term_days

  enum status: [:enabled, :disabled]
end

app/controllers/services_controller.rb
class ServicesController < AuthedAppController
  before_action :require_is_marketing
  # before_action :set_service, except: [:index, :new, :create]
  before_action :set_service, except: [:index, :create]
  before_action :set_all_services, except: []

  def index
  end

  def create
    @service = Service.new(service_params)
    @service.save
    render :index
  end

  def update
    @service.update_attributes(service_params)
    redirect_to services_path
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path
  end

  def disable
    @service.disabled!
    redirect_to services_path
  end

  def enable
    @service.enabled!
    redirect_to services_path
  end

protected
  def set_service
    @service = Service.find(params[:id] || params[:service_id])
  end

  def service_params
    params.require(:service).permit(:name, :price, :description, :early_term_fee)
  end

  def set_all_services
    @services = Service.all
  end
end

app/views/services/index.html.erb
<div class="services-index">
  <% if @service && @service.errors.any? %>
    <ul class="errors">
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <% (@services + [Service.new]).each do |service| %>
    <div class="thing-tile">
      <% if service.new_record? %>
        New Service
      <% end %>
      <%= form_for service do |f| %>
        <header>
          <em><%= service.id %></em>
          <%= f.text_field :name, placeholder: "Service Name" %>
        </header>
        <div class="price">
          <%= f.label :price %>
          <%= f.text_field :price %>
        </div>
        <div class="early-term">
          <%= f.label :early_term_fee %>
          $<%= f.number_field :early_term_fee, step: "any" %>
        </div>
        <div>
          <%= f.text_area :description, placeholder: "Service Description" %>
        </div>
        <div class="submit">
          <%= f.submit %>
        </div>
      <% end %>
      <% if service.persisted? %>
        <% if service.disabled? %>
          <%= button_to "Enable Service", service_enable_path(service) %>
        <% else %>
          <%= button_to "Disable Service", service_disable_path(service) %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>