config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show, :index] do
    post "generate_bill"
  end
  resources :bills, only: [] do
    post "pay"
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    post "create_for/:user_id", on: :collection, as: :create_for, action: :create_for
    post "clone_package/:user_id", as: :clone_package, action: :clone_package
  end
  resources :services, except: [:new, :edit] do
    post "disable"
    post "enable"
  end
  resources :packages

  authenticated :user do
    devise_scope :user do
      root to: "dashboard#overview", as: :root_authed
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", as: :root_unauthed
    end
  end

  resources :subscription_rules, only: [:index, :create, :update]

end

app/controllers/dashboard_controller.rb
class DashboardController < AuthedAppController

  def overview
    @user = current_user
  end
end

app/views/dashboard/_customer_overview.html.erb
<p>Summary of account, services, packages, etc here.</p>

<p>Your subscriptions:</p>
<% @user.subscriptions.each do |sub| %>
  <% subscribable = sub.subscribable %>
  <div class="bill">
    <div class="thing-tile">
      <header><%= subscribable.name %></header>
      <em><%= subscribable.price %></em>
      <footer>Terminates On: <%= sub.pretty_term_date %> (fee: <%= number_to_currency sub.early_term_fee %>) </footer>
    </div>
    <%= button_to "Unsubscribe", subscription_path(sub), method: :delete %>
  </div>
<% end %>

<% bills = @user.bills.unpaid.order(created_at: :desc) %>
<% if bills.any? %>
  <h2>Your bills (total debt: <%= number_to_currency bills.map(&:cost).inject(0, &:+) %>)</h2>
<% end %>
<% bills.each do |bill| %>
  <div class="bill">
    <p>Bill, generated on <%= bill.pretty_date %>: </p>
    <div class="bill">
      <table>
        <tr>
          <td>Service Name</td>
          <td>Price</td>
        </tr>

        <% odd = false %>
        <% bill.toplevel_bill_items.each do |bi| %>
          <% odd = !odd %>
          <tr class="<%= odd ? "odd" : "even" %>">
            <td><%= bi.name %></td>
            <td><%= number_to_currency bi.price %></td>
          </tr>

          <% bi.service_bill_items.each do |bsi| %>
            <% odd = !odd %>
            <tr class="<%= odd ? "odd" : "even" %>">
              <td>&rarr;<em><%= bsi.name %></em></td>
              <td>---</td>
            </tr>
          <% end %>
        <% end %>
      </table>
      <p>Total cost: <em><%= number_to_currency bill.cost %></em></p>
      <%= button_to "Pay Bill", bill_pay_path(bill) %>
    </div>
  </div>
<% end %>

app/views/dashboard/_customer_service_overview.html.erb
Welcome, customer service rep <%= user.name %><br>

Here's a list of customers:
<% User.customers.each do |user| %>
  <div class="user">
    <header>
      <div>Name: <%= user.name %>, <b><%= user.email %></b></div>
      <div>Account Type: <b><%= user.account_type_string %></b></div>
    </header>
    <%= link_to "Manage User", user_path(user) %>
  </div>
<% end %>

app/views/dashboard/_header.html.erb
<div class="dashboard-header">
  <div class="logo">
    <h4>PT&amp;T &copy; 2015</h4>
  </div>
  <div class="welcome">
    <span class="name">
      Welcome, <em><%= user.name %></em>
      (<%= user.account_type_string %>)
    </span>
    <%= link_to "Sign Out", destroy_user_session_path %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </div>
</div>

app/views/dashboard/_marketing_overview.html.erb
Welcome, marketing rep <%= user.name %>

app/views/dashboard/_sidebar.html.erb
<nav class="dashboard-sidebar">
  <ul>
    <% if @user.marketing? %>
      <li><%= link_to "Overview", root_authed_path %></li>
      <li><%= link_to "Manage Packages", packages_path %></li>
      <li><%= link_to "Manage Services", services_path %></li>
      <li><%= link_to "Manage Subscription Rules", subscription_rules_path %></li>
    <% elsif @user.customer_service? %>
      <li><%= link_to "Overview", root_authed_path %></li>
    <% else %>
      <li><%= link_to "Overview", root_authed_path %></li>
      <li><%= link_to "Manage My Account", edit_user_registration_path %></li>
      <li><%= link_to "Manage my Subscriptions", subscriptions_path %></li>
    <% end %>
  </ul>
</nav>

app/views/dashboard/overview.html.erb
<% if @user.marketing? %>
  <%= render "marketing_overview", user: @user %>
<% elsif @user.customer_service? %>
  <%= render "customer_service_overview", user: @user %>
<% else %>
  <%= render "customer_overview", user: @user %>
<% end %>